name: Deploy
on:
  push: {}
  schedule:
    - cron: "*/15 * * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          submodules: "true"
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.87.0"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-duration-seconds: 1200
          role-skip-session-tagging: true
      - name: copy uptimes
        shell: bash
        run: aws s3 cp s3://${{ secrets.AWS_UPTIME_BUCKET }}/${{ secrets.AWS_UPTIME_KEY }} ./data/uptimes.json
      - run: hugo new -k uptime ./content/issues/_uptime.md
      - run: hugo --minify
      - uses: actions/checkout@v2.1.0
        with:
          repository: botpress/actions
          token: ${{ secrets.BOTPRESSOPS_PAT }}
          path: "@actions"
      - uses: "./@actions/deploy/s3-website"
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          source: ./public
          bucket: ${{ secrets.AWS_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
