name: Deploy
on:
  push: {}
  schedule:
    - cron: "*/5 * * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          submodules: "true"
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.87.0"
      - run: hugo --minify
      - uses: actions/checkout@v2.1.0
        with:
          repository: botpress/actions
          token: ${{ secrets.BOTPRESSOPS_PAT }}
          path: "@actions"
      - uses: "./@actions/deploy/s3-website"
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          source: ./public
          bucket: ${{ secrets.AWS_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
